# -*- coding: utf-8 -*-
"""draft_backend.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rIZmzix3Jd1SS8BywuyblaVn2E5xp04S

## Set up LLM
"""

!pip install -qU langgraph langchain-google-genai langchain-community tavily-python langchain-tavily
!pip install -qU langchain-openrouter
!pip install PyMuPDF
# Colab needs a restart before newly installed packages are importable.
import sys
if 'langchain_google_genai' not in sys.modules:
    print('Packages installed — restarting runtime (this is normal!)')
    import os; os.kill(os.getpid(), 9)

"""## Library

"""

import fitz
import os
from google.colab import userdata
from openrouter import OpenRouter
from langchain_openrouter import ChatOpenRouter
from langchain_core.rate_limiters import InMemoryRateLimiter
from langchain_tavily import TavilySearch
from langchain_core.tools import tool
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langgraph.prebuilt import create_react_agent
from langchain_core.output_parsers import StrOutputParser
from typing import TypedDict, Annotated, Sequence
from langgraph.graph import StateGraph, END
from langchain_core.messages import BaseMessage, HumanMessage, AIMessage
import operator
from langgraph.graph import StateGraph, START, END

# Reads from your private Colab Secrets, never touches the notebook
os.environ["GOOGLE_API_KEY"] = userdata.get("GOOGLE_API_KEY")
os.environ["TAVILY_API_KEY"] = userdata.get("TAVILY_API_KEY")
os.environ["OPENROUTER_API_KEY"] = userdata.get("OPENROUTER_API_KEY_3")

rate_limiter = InMemoryRateLimiter(
    requests_per_second=0.3,
    check_every_n_seconds=0.1,
)

# For writing tasks
writing_llm = ChatOpenRouter(
    model="openrouter/free",
    temperature=0.7, # Slightly higher for more natural, creative writing
    rate_limiter=rate_limiter
)

# For feedback/critique tasks
reasoning_llm = ChatOpenRouter(
    model="openrouter/free",
    temperature=0, # Keep at 0 for focused, analytical critique
    rate_limiter=rate_limiter
)

# For chatbot
chat_llm = ChatOpenRouter(
    model="meta-llama/llama-4-scout:free", # Swap with any model above
    temperature=0.7, # 0.7 is perfect for conversational variety
)

"""## Insert system prompt

"""

feedback_prompt = """**System Prompt:** Act as a Senior Technical Recruiter and Career Coach specializing in Computer Science and STEM fields. Your objective is to review the provided student resume and provide actionable, highly specific, and ruthless feedback to help them land top-tier internships, new grad roles, or prestigious research positions.

Please follow this step-by-step process for your review:

### **Step 1: Structural, ATS, Red Flags, & Immigration Logistics**
*   **ATS & AI Scanner Check:** Evaluate the format. HR software cannot read complex columns, graphics, or weird fonts. Warn the student if their layout will fail an ATS parser.
*   **The "Fluff" Cut:** Identify any sections that are unnecessarily long. Tell them exactly what to delete (e.g., high school achievements if they are a Junior/Senior, irrelevant non-technical jobs, or obvious skills like "Microsoft Word").
*   **Red Flags & Gaps:** Point out any unexplained gaps in education or employment, and check their GPA. If it is below a 3.0 (or 3.2 depending on the rigor of the major), advise them to remove it.
*   **International Student / Visa Check:** Look for indicators of international status. If the student is an international student, provide advice explicitly tailored to navigating CPT/OPT requirements.
*   **Resume vs. CV Check:** Determine if their format aligns with an industry Resume (strict 1-page, impact-focused) or an academic CV (research-focused, longer). Advise them based on standard guidelines from top institutions like Penn and Columbia.

### **Step 2: Project Impact & LinkedIn Benchmarking**
*   **LinkedIn Benchmark:** Compare this resume's caliber against the typical LinkedIn profile of an incoming FAANG software engineering intern or a Quant firm intern. Tell the user explicitly where they fall short of that standard.
*   **Evaluate Project Impact:** Analyze the "Projects" and "Experience" sections. Do they highlight the *impact* of their work using the STAR method? Push for quantifiable metrics (e.g., "reduced latency by 15%").
*   **Assess Storytelling:** Advise the candidate on how to structure their bullets to tell a compelling story for HR behavioral interviews (identifying the technical challenge, the trade-offs, and the resolution).

### **Step 3: Extracurricular, Leadership, & Campus Context Analysis**
*   Identify the student's University and Major from the resume.
*   **Do not give generic advice.** You must search for and suggest the *exact, actual names* of organizations at their specific university that align directly with their major.
*   **Time Management Acknowledgment:** Recognize that students have limited time for extracurricular activities. Present the following categories as a *list of options to consider*, advising them to choose 1 or 2 high-impact activities that best suit their schedule and career goals, rather than trying to do everything.
    *   *Software/General:* Hackathons (e.g., MLH events), university ACM/ACM-W chapters, or cybersecurity teams (CTFs).
    *   *Open Source & Independent Work:* Suggest joining university-affiliated open-source groups. *Example for OSU:* Suggest the "Center for Applied Systems and Software (CASS)". Alternatively, highly recommend actively contributing to open-source projects or polishing and publishing their own projects on GitHub to build a public portfolio.
    *   *Robotics & Hardware:* Search for their university's autonomous racing team (Formula SAE Driverless), Mars Rover team, RoboCup, or underwater ROV teams. *Example for OSU:* Suggest "DAM Robotics", "OSURC", or "Global Formula Racing".
    *   *Leadership & Development Programs:* Suggest official university leadership, mentorship, or ambassador programs to build soft skills. *Example for OSU:* Suggest applying for the "LEAP program" or becoming an Engineering/Science Ambassador.
    *   *Niche/Theoretical:* Suggest relevant intercollegiate competitions: Student Cluster Competition (HPC), Putnam/ICPC (Math/Algos), Kaggle (Data/AI), Directed Reading program (Math/Academic).

### **Step 4: Prestige Internships, Research, & Academic Strategy**
Review their trajectory and suggest high-value targets to aim for based on their **Class Standing**, keeping citizenship restrictions in mind:
*   **University-Specific Co-ops:** Identify if their university has a specific cooperative education program. *Example for OSU:* Explicitly tell them to apply for the "MECOP Program". (If international, remind them to coordinate with their international student office early for CPT approval).
*   **Prestige Internships:** Suggest elite programs to target. *Underclassmen:* Google STEP, Meta University, Microsoft Explore. *Upperclassmen:* FAANG, Jane Street, NASA. (If international, steer away from ITAR/defense and toward tech/quant).
*   **Early-Career vs. Advanced Research:** Suggest research opportunities tailored to their year.
    *   *Freshmen/Sophomores:* Search for early-undergrad research incubator programs at their school. *Example for OSU:* Explicitly recommend applying to the "URSA Engage" program.
    *   *Juniors/Seniors:* Recommend applying for the Department of Energy's SULI program (National Labs like Oak Ridge, Lawrence Berkeley), or university-level REUs/SURF.
*   **Academic Roles:** Advise them to build relationships with professors by becoming a **Research Assistant**. Suggest applying to be an **Undergraduate Learning Assistant (ULA) / TA**, or a **Course Grader**.

### **Output Format:**
Present your feedback clearly using Markdown, with the following distinct sections:
1.  **The Brutal Truth: ATS, Formatting, Gaps & Visa Strategy**
2.  **LinkedIn Benchmark & Project Impact**
3.  **Tailored Extracurricular & Leadership Guide**
4.  **Target List: Co-ops, Research (By Year) & Academic Roles**
5.  **Semester Action Plan (Top 3 Priorities)**

Keep your tone professional, encouraging, but relentlessly candid. Do not sugarcoat weaknesses.

***

**Here is the resume to review:**
Resume: {resume}"""


company_prompt = """Act as a Senior Business Analyst. Review the target company and extract a concise summary for a downstream AI writing agent.
Focus strictly on:
1. The company's core mission and primary product.
2. Their cultural values (e.g., 'move fast', 'academic', 'customer-obsessed').
3. Recent strategic news or why they are currently hiring.
Keep it strictly under 150 words.

Target Company: {company}
"""



cross_reference_prompt = """Act as an ATS (Applicant Tracking System) optimizer. Compare the candidate's resume against the target job description.
Identify specific keywords, tools, or critical skills from the job description that are missing from the resume.
Provide exactly 3 actionable suggestions on how the candidate can tweak their existing resume bullets to better match this specific role.

Resume:
{resume}

Job Description:
{job}"""



generate_letter_prompt = """Act as an expert Career Coach. Write a highly tailored, professional cover letter for the candidate.

You have been provided with:
1. The candidate's Resume.
2. The exact Job Description.
3. A summary of the Company's culture and goals.
4. Insights mapping the candidate's skills to the role.

INSTRUCTIONS:
- Use the 'Company Summary' to align the tone with their corporate culture.
- Use the 'Cross Reference Insights' to highlight the candidate's most relevant project.
- Keep it under 300 words. No robotic jargon (e.g., 'delve', 'testament').

Company Summary:
{company_result}

Cross Reference Insights:
{JDMatch_result}

Resume: {resume}
Job Description: {job}"""


# Node: Generate msg
generate_msg_prompt = """Act as a Career Coach. Write a brief networking message to a recruiter.

INSTRUCTIONS:
- Highlight a match from the 'Cross Reference Insights'.
- Reference a cultural trait or goal from the 'Company Summary' to show insider knowledge.
- STRICT LIMIT: Must be between 75 and 95 words. Do not exceed 100 words.

Company Summary:
{company_result}

Cross Reference Insights:
{JDMatch_result}

Resume: {resume}
Job Description: {job}"""



############### CHATBOT #######################
feedback_chatbot_prompt = ""
msg_chatbot_prompt = ""
letter_chatbot_prompt = ""

"""## Give agents tools


"""

# Initialize once globally
web_search = TavilySearch(max_results=5)

@tool
def company_search(query: str) -> str:
    """Search for recent news, hiring trends, and work culture about a company."""

    # Run the searches
    do_results = web_search.invoke(f"What {query} do in 2025 2026?")
    hire_results = web_search.invoke(f"Why {query} are hiring right now?")
    culture_results = web_search.invoke(f"What {query} 's work culture?")

    # Extract JUST the text content, joined by spaces or newlines
    what_they_do = " ".join([res.get("content", "") for res in do_results.get("results", [])])
    why_they_hiring = " ".join([res.get("content", "") for res in hire_results.get("results", [])])
    work_culture = " ".join([res.get("content", "") for res in culture_results.get("results", [])])

    # Format into a clean string for the LLM
    results = (
        f"What they do: {what_they_do}\n"
        f"Why they are hiring: {why_they_hiring}\n"
        f"Work culture: {work_culture}"
    )

    return results

"""## Encode and Decode images"""

def extract_text_from_pdf(pdf_path: str) -> str:
    """Extracts and formats text from a PDF document."""
    extracted_text = ""

    try:
        # Open the document
        with fitz.open(pdf_path) as pdf_doc:
            for page_num in range(len(pdf_doc)):
                page = pdf_doc[page_num]
                # Extract text preserving the logical reading order as best as possible
                extracted_text += page.get_text("text") + "\n\n"

        return extracted_text.strip()

    except Exception as e:
        return f"Error reading PDF: {e}"

"""## Build the specialist agents

"""

parser = StrOutputParser()

def make_agent(system_prompt: str, model: str, tools: list, name: str):
    """Factory function: creates a named agent with a role and toolset."""
    return create_react_agent(
        model=model,
        tools=tools,
        prompt=system_prompt,
        name=name,
    )

# Research Company: Find new information about a specific company
ResearchCompany = make_agent(
    system_prompt= company_prompt,
    model = reasoning_llm,
    tools=[company_search],
    name="ResearchCompany"
)


feedback_template = ChatPromptTemplate.from_messages([
    ("system", feedback_prompt),
    ("user", "Here is the resume to review: {resume}")
])
resume_feedback_chain = feedback_template | reasoning_llm | parser


crossref_template = ChatPromptTemplate.from_messages([
    ("system", cross_reference_prompt),
    ("user", "Job description: {job}\n\nResume: {resume}")
])
crossref_chain = crossref_template | reasoning_llm | parser


letter_template = ChatPromptTemplate.from_messages([
    ("system", generate_letter_prompt),
    ("user", "JD Match info: {JDMatch_result}\nCompany info: {company_result}\nResume: {resume}")
])
generate_letter_chain = letter_template | writing_llm | parser


msg_template = ChatPromptTemplate.from_messages([
    ("system", generate_msg_prompt),
    ("user", "JD Match info: {JDMatch_result}\nCompany info: {company_result}\nResume: {resume}")
])
generate_msg_chain = msg_template | writing_llm | parser

# State: shared memory passed between all agents
class AgentState(TypedDict):
    job: str                                            # The job being researched
    company: str					                              # The company being researched
    resume: str						                              # Turn pdf into string
    company_result: str                                 # Output from ResearchCompany
    JDMatch_result: str                                 # Output from CrossRef
    feedback_result: str                                # Output from ResumeFeedback
    cover_letter_result: str                            # Output from GenerateLetter
    msg_result: str					                            # Output from GenerateMsg


# Node functions: each runs one agent and updates state

def run_ResearchCompany(state: AgentState) -> dict:
    # This stays as an agent because it uses the company_search tool
    result = ResearchCompany.invoke(
        {"messages": [("user", f"Find information about {state['company']}")]}
    )
    return {"company_result": result["messages"][-1].content}

def run_ResumeFeedback(state: AgentState) -> dict:
    # Using the LCEL chain
    result_str = resume_feedback_chain.invoke({"resume": state['resume']})
    return {"feedback_result": result_str}

def run_CrossRef(state: AgentState) -> dict:
    # Using the LCEL chain
    result_str = crossref_chain.invoke({
        "job": state['job'],
        "resume": state['resume']
    })
    return {"JDMatch_result": result_str}

def run_GenerateLetter(state: AgentState) -> dict:
    # Using the LCEL chain
    result_str = generate_letter_chain.invoke({
        "JDMatch_result": state['JDMatch_result'],
        "company_result": state['company_result'],
        "resume": state['resume'],
        "job": state['job']
    })
    return {"cover_letter_result": result_str}

def run_GenerateMsg(state: AgentState) -> dict:
    # Using the LCEL chain
    result_str = generate_msg_chain.invoke({
        "JDMatch_result": state['JDMatch_result'],
        "company_result": state['company_result'],
        "resume": state['resume'],
        "job": state['job']
    })
    return {"msg_result": result_str}

# 1. Initialize the graph with your AgentState
workflow = StateGraph(AgentState)

# 2. Add all your configured nodes
workflow.add_node("ResearchCompany", run_ResearchCompany)
workflow.add_node("ResumeFeedback", run_ResumeFeedback)
workflow.add_node("CrossRef", run_CrossRef)
workflow.add_node("GenerateLetter", run_GenerateLetter)
workflow.add_node("GenerateMsg", run_GenerateMsg)

workflow.add_edge(START, "ResearchCompany")
workflow.add_edge(START, "ResumeFeedback")
workflow.add_edge(START, "CrossRef")

# Generate Letter and Msg wait for both Research and CrossRef to finish
# (LangGraph handles this automatically if you don't map them sequentially)
workflow.add_edge("ResearchCompany", "GenerateLetter")
workflow.add_edge("CrossRef", "GenerateLetter")

workflow.add_edge("ResearchCompany", "GenerateMsg")
workflow.add_edge("CrossRef", "GenerateMsg")

# End the graph
workflow.add_edge("ResumeFeedback", END)
workflow.add_edge("GenerateLetter", END)
workflow.add_edge("GenerateMsg", END)

app = workflow.compile()

"""## Run it!


"""

# Change this to any company you want to research!
user_company = "Nebius"
user_job = "Junior Software Engineer"
pdf_filename = "resume.pdf"
user_resume = extract_text_from_pdf(pdf_filename)

print("=" * 60)
print()

# Run the graph
result = app.invoke({
    "job": user_job,
    "company": user_company,
    "resume": user_resume,
    "company_result": "",
    "JDMatch_result": "",
    "feedback_result": "",
    "cover_letter_result": "",
    "msg_result": "",
})

print()
print("=" * 60)
print(f"Analysis complete!")
print(result['feedback_result'])
print("=" * 60)
print(result['JDMatch_result'])

print(result['msg_result'])

print(result['cover_letter_result'])

print(result['JDMatch_result'])